version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      PORT: 3000
      DB_IP: mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
